flutter_version: stable
is_configured: true
pipeline_steps:
  building:
  - cd $BUILD_DIR
  - flutter build apk --debug
  - flutter build ios --debug --no-codesign
  publishing:
    emails:
    - andrjuwkoy@gmail.com
    slack: {}
  testing:
  - cd $BUILD_DIR
  - flutter test
platforms:
- android
- ios
xcode_version: latest
